[package]
name = "livi-dongle"
version = "0.1.0"
edition.workspace = true

[dependencies]
livi-session-io = { path = "../livi-session-io" }
futures-util = "0.3"
nusb = { version = "0.2", features = ["tokio"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "macros", "time", "sync", "io-util", "net"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync", "io-util", "net", "test-util"] }
