import json
import os
from pathlib import Path


def _get_config_path() -> Path:
    original_user = os.environ.get("SUDO_USER", os.environ.get("USER", ""))
    if original_user and original_user != "root":
        return Path(f"/home/{original_user}") / ".config" / "LIVI" / "config.json"
    return Path.home() / ".config" / "LIVI" / "config.json"


def _load_from_json() -> dict:
    config_path = _get_config_path()
    try:
        with open(config_path) as f:
            data = json.load(f)
            print(f"[config] loaded from {config_path}")
            return data
    except FileNotFoundError:
        print(f"[config] no config.json found at {config_path}")
    except json.JSONDecodeError as e:
        print(f"[config] error parsing {config_path}: {e}")
    return {}


_JSON_CONFIG = _load_from_json()

DEVICES_FILE = _get_config_path().parent / "devices.json"


def _get_value(key: str, json_key: str, default: str) -> str:
    """config.json, then env var, then default."""
    val = _JSON_CONFIG.get(json_key, "")
    if val:
        return str(val)
    env_val = os.environ.get(key, "")
    if env_val:
        return env_val
    return default


# Wi-Fi AP
SSID = _get_value("LIVI_SSID", "carName", "LIVI")
PASSPHRASE = _get_value("LIVI_PASSPHRASE", "wifiPassword", "12345678")
CHANNEL = int(_get_value("LIVI_CHANNEL", "wifiChannel", "36"))
COUNTRY_CODE = _get_value("LIVI_COUNTRY", "country", "DE")
WIFI_IFACE = _get_value("LIVI_WIFI_IFACE", "wifiInterface", "wlan0")
SECURITY_TYPE = "WPA_WPA2"

# Bluetooth
BTNAME = _get_value("LIVI_BTNAME", "carName", "LIVI")
BT_ADAPTER = _get_value("LIVI_BT_ADAPTER", "btAdapter", "hci0")

# CarPlay MFi authentication coprocessor over i2c
MFI_I2C_BUS = int(_get_value("LIVI_CP_MFI_I2C_BUS", "carPlayMfiI2cBus", "2"))
MFI_POWER_GPIO = _get_value("LIVI_CP_MFI_POWER_GPIO", "carPlayMfiPowerGpio", "21")

# CarPlay charging current advertised to the phone over the wired link (mA)
_ALLOWED_CURRENTS_MA = (0, 500, 1000, 1500, 2100, 2400, 3000)
AVAILABLE_CURRENT_MA = int(_get_value("LIVI_CP_AVAILABLE_CURRENT_MA", "carPlayAvailableCurrentMa", "500"))
if AVAILABLE_CURRENT_MA not in _ALLOWED_CURRENTS_MA:
    AVAILABLE_CURRENT_MA = 500

CARPLAY_WIRED_START_SESSION = _get_value(
    "LIVI_CP_WIRED_START_SESSION", "carPlayWiredStartSession", "1") not in ("", "0", "false", "False")
CARPLAY_SOURCE_VERSION = _get_value("LIVI_CP_SOURCE_VERSION", "carPlaySourceVersion", "950.7.1")

# CarPlay AirPlay / Bonjour
AIRPLAY_PORT = 7000

# CarPlay AirPlay-2 pairing identity (generated by the supervisor, env only)
PK = os.environ.get("LIVI_CP_PK", "")
PI = os.environ.get("LIVI_CP_PI", "")

# CarPlay WAC metadata advertised to the phone
MANUFACTURER = "LIVI"
MODEL = "LIVI"
DEVICE_ID = "12345678"
NAME = _get_value("LIVI_CP_NAME", "carName", "LIVI")

# Verbose per-packet logging
DEBUG = os.environ.get("LIVI_CP_DEBUG", os.environ.get("DEBUG", "")) not in ("", "0", "false", "False")

# iPhone syslog tap over LIVI's usbmux socket (opt-in, wired teardown diagnosis)
CP_SYSLOG_TAP = os.environ.get("LIVI_CP_SYSLOG", "") not in ("", "0", "false", "False")
