#!/usr/bin/env python3
# Enable HEVC decoder + parser in chromium/third_party/ffmpeg's "Chrome"
# branding. Chromium's Chrome-branding FFmpeg config intentionally excludes
# HEVC because it expects HEVC to come from platform paths (VAAPI on Linux,
# VideoToolbox on macOS, MediaFoundation on Windows). For systems without
# a HW HEVC backend (Raspberry Pi etc.) we need the SW path through
# libffmpeg's libavcodec. This script flips the relevant CONFIG flags,
# adds entries to codec_list.c / parser_list.c / bsf_list.c, and inserts
# the HEVC source files into ffmpeg_generated.gni so they get compiled.
#
# Run after `gclient sync` and before `gn gen` from chromium/src.
#
#   python3 .../enable-hevc.py /mnt/build/chromium/src/third_party/ffmpeg
#
from __future__ import annotations

import re
import sys
from pathlib import Path

# CONFIG_* flags HEVC needs at runtime. All forced to 1
HEVC_DEFINES = [
    'CONFIG_HEVC_DECODER',
    'CONFIG_HEVC_PARSER',
    'CONFIG_HEVCPARSE',
    'CONFIG_HEVC_SEI',
    'CONFIG_HEVC_MP4TOANNEXB_BSF',
    'CONFIG_HEVC_DEMUXER',
]

# C sources in libavcodec/ root that have unique basenames
HEVC_C_SOURCES_DIRECT = [
    'libavcodec/bsf/hevc_mp4toannexb.c',
    'libavcodec/bswapdsp.c',
    'libavcodec/aom_film_grain.c',
    'libavcodec/dovi_rpu.c',
    'libavcodec/dovi_rpudec.c',
    'libavcodec/dynamic_hdr_vivid.c',
]

SIMD_STUB_REL_PATH = 'libavcodec/hevc_simd_stubs.c'
SIMD_STUB_CONTENT = '''// Auto-generated by enable-hevc.py.
// Empty implementations to satisfy the linker for HEVC SW-only builds.
// Replace with real arch-specific SIMD init when adding NEON/SSE2 sources.
#include "config.h"

struct HEVCDSPContext;
struct BswapDSPContext;

#if ARCH_X86
void ff_hevc_dsp_init_x86(struct HEVCDSPContext *hevcdsp, const int bit_depth) {}
void ff_bswapdsp_init_x86(struct BswapDSPContext *c) {}
#endif

#if ARCH_AARCH64
void ff_hevc_dsp_init_aarch64(struct HEVCDSPContext *hevcdsp, const int bit_depth) {}
void ff_bswapdsp_init_aarch64(struct BswapDSPContext *c) {}
#endif

#if ARCH_ARM
void ff_hevc_dsp_init_arm(struct HEVCDSPContext *hevcdsp, const int bit_depth) {}
void ff_bswapdsp_init_arm(struct BswapDSPContext *c) {}
#endif

#if ARCH_RISCV
void ff_bswapdsp_init_riscv(struct BswapDSPContext *c) {}
#endif
'''

# C sources under libavcodec/hevc/
HEVC_C_SOURCES_AUTORENAME = [
    'cabac.c',
    'data.c',
    'dsp.c',
    'filter.c',
    'hevcdec.c',
    'mvs.c',
    'parse.c',
    'parser.c',
    'pred.c',
    'ps.c',
    'refs.c',
    'sei.c',
]

TARGET_CONFIG_DIRS = [
    'chromium/config/Chrome/linux/x64',
    'chromium/config/Chrome/linux/arm64',
]


def patch_config_h(cfg_path: Path) -> bool:
    """Flip existing CONFIG_HEVC_* defines to 1 and append missing ones."""
    if not cfg_path.is_file():
        return False
    src = cfg_path.read_text()
    out = src
    for name in HEVC_DEFINES:
        # Replace `#define <NAME> 0` with `#define <NAME> 1`
        out = re.sub(
            rf'^(#define {re.escape(name)})\s+0$',
            r'\1 1',
            out,
            flags=re.MULTILINE,
        )
    appended = []
    for name in HEVC_DEFINES:
        if not re.search(rf'^#define {re.escape(name)}\s', out, flags=re.MULTILINE):
            appended.append(f'#define {name} 1')
    if appended:
        if not out.endswith('\n'):
            out += '\n'
        out += '\n'.join(appended) + '\n'
    if out != src:
        cfg_path.write_text(out)
        return True
    return False


def insert_into_list(
    list_path: Path,
    entry: str,
    anchor_re: str,
) -> bool:
    """Insert `entry` after the first line matching `anchor_re` if not yet present."""
    if not list_path.is_file():
        return False
    src = list_path.read_text()
    if entry in src:
        return False
    m = re.search(anchor_re, src, flags=re.MULTILINE)
    if not m:
        # Empty list (just `NULL`)? insert before NULL terminator.
        out = re.sub(
            r'(    )?NULL\s*\}\s*;',
            f'    {entry}\n    NULL }};',
            src,
            count=1,
        )
        if out == src:
            sys.stderr.write(
                f'WARN: could not patch {list_path} — no anchor `{anchor_re}` and no NULL terminator\n'
            )
            return False
    else:
        # Insert right after the anchor line.
        end = m.end()
        out = src[:end] + f'\n    {entry}' + src[end:]
    list_path.write_text(out)
    return True


def patch_lists(cfg_dir: Path) -> None:
    insert_into_list(
        cfg_dir / 'libavcodec/codec_list.c',
        '&ff_hevc_decoder,',
        anchor_re=r'^\s*&ff_h264_decoder,\s*$',
    )
    insert_into_list(
        cfg_dir / 'libavcodec/parser_list.c',
        '&ff_hevc_parser,',
        anchor_re=r'^\s*&ff_h264_parser,\s*$',
    )
    insert_into_list(
        cfg_dir / 'libavcodec/bsf_list.c',
        '&ff_hevc_mp4toannexb_bsf,',
        anchor_re=r'^\s*&ff_[a-z0-9_]+_bsf,\s*$',
    )


def autorename_path(basename: str) -> str:
    """Per Chromium convention: libavcodec/autorename_libavcodec_hevc_<base>.c"""
    return f'libavcodec/autorename_libavcodec_hevc_{basename}'


def write_simd_stub(ffmpeg_dir: Path) -> bool:
    """Drop the SIMD-init stub file. Idempotent."""
    stub = ffmpeg_dir / SIMD_STUB_REL_PATH
    if stub.is_file():
        return False
    stub.write_text(SIMD_STUB_CONTENT)
    return True


def write_autorename_wrappers(ffmpeg_dir: Path) -> int:
    """Drop one #include-only wrapper per autorename source. Idempotent."""
    written = 0
    for base in HEVC_C_SOURCES_AUTORENAME:
        wrapper = ffmpeg_dir / autorename_path(base)
        target = ffmpeg_dir / 'libavcodec' / 'hevc' / base
        if not target.is_file():
            sys.stderr.write(f'WARN: source not found: {target}\n')
            continue
        if wrapper.is_file():
            continue
        # Match the include-style of existing autorename wrappers Chromium ships.
        wrapper.write_text(
            f'// Auto-generated wrapper to avoid object file collision with '
            f'libavcodec/{base}.\n'
            f'#include "../../third_party/ffmpeg/libavcodec/hevc/{base}"\n'
        )
        written += 1
    return written


def patch_chromium_ffmpeg_video_decoder(chromium_src: Path) -> bool:
    """Lift the Chromium-side gate that hardcodes FFmpegVideoDecoder to H.264."""
    target = chromium_src / 'media' / 'filters' / 'ffmpeg_video_decoder.cc'
    if not target.is_file():
        sys.stderr.write(f'ERROR: {target} not found\n')
        return False
    src = target.read_text()
    marker = '// HEVC enabled by enable-hevc.py'
    if marker in src:
        return False

    # Patch 1: IsCodecSupported — accept HEVC alongside H.264.
    p1_old = (
        'bool FFmpegVideoDecoder::IsCodecSupported(VideoCodec codec) {\n'
        '  // We only build support for H.264.\n'
        '  return codec == VideoCodec::kH264 && IsDecoderBuiltInVideoCodec(codec);\n'
        '}'
    )
    p1_new = (
        'bool FFmpegVideoDecoder::IsCodecSupported(VideoCodec codec) {\n'
        f'  {marker}\n'
        '  return (codec == VideoCodec::kH264 || codec == VideoCodec::kHEVC) &&\n'
        '         IsDecoderBuiltInVideoCodec(codec);\n'
        '}'
    )
    if p1_old not in src:
        sys.stderr.write(
            'ERROR: IsCodecSupported pattern not found — Chromium media layout '
            'may have shifted. Review media/filters/ffmpeg_video_decoder.cc and '
            'update this script.\n'
        )
        return False

    # Patch 2: GetFFmpegVideoDecoderThreadCount
    p2_old = (
        '    case VideoCodec::kHEVC:\n'
        '    case VideoCodec::kVP9:\n'
    )
    p2_new = (
        '    case VideoCodec::kVP9:\n'
    )
    # The kH264 line we want to patch is the one INSIDE the switch — anchored
    # by the preceding NOTREACHED() block to avoid hitting the H264 in the
    # IsCodecSupported function above.
    p3_old = (
        '      NOTREACHED();\n'
        '\n'
        '    case VideoCodec::kH264:\n'
    )
    p3_new = (
        '      NOTREACHED();\n'
        '\n'
        '    case VideoCodec::kH264:\n'
        '    case VideoCodec::kHEVC:\n'
    )

    if p2_old not in src or p3_old not in src:
        sys.stderr.write(
            'ERROR: GetFFmpegVideoDecoderThreadCount switch layout has '
            'shifted — review media/filters/ffmpeg_video_decoder.cc.\n'
        )
        return False

    out = src.replace(p1_old, p1_new, 1)
    out = out.replace(p2_old, p2_new, 1)
    out = out.replace(p3_old, p3_new, 1)
    target.write_text(out)
    return True


def patch_build_gn(build_gn_path: Path) -> bool:
    """Add `libavcodec` to ffmpeg_internal's include_dirs."""
    if not build_gn_path.is_file():
        sys.stderr.write(f'ERROR: {build_gn_path} not found\n')
        return False
    src = build_gn_path.read_text()
    marker = '"libavcodec",  # added by enable-hevc.py'
    if marker in src:
        return False

    pattern = re.compile(
        r'(target\(link_target_type, "ffmpeg_internal"\) \{[\s\S]*?include_dirs = \[\s*\n'
        r'\s*platform_config_root,\s*\n'
        r'\s*"\.",\s*\n)(\s*\])'
    )
    m = pattern.search(src)
    if not m:
        sys.stderr.write(
            'ERROR: could not locate ffmpeg_internal include_dirs in BUILD.gn '
            '(layout may have shifted upstream)\n'
        )
        return False
    insert = f'    {marker}\n'
    out = src[:m.start(2)] + insert + src[m.start(2):]
    build_gn_path.write_text(out)
    return True


def patch_generated_gni(gni_path: Path) -> bool:
    """Append HEVC C sources to the generic Chrome-branding block (the one
    bracketed by `if (... && ffmpeg_branding == "Chrome") {`).
    """
    if not gni_path.is_file():
        sys.stderr.write(f'ERROR: {gni_path} not found\n')
        return False
    src = gni_path.read_text()
    if 'autorename_libavcodec_hevc_hevcdec.c' in src:
        return False

    anchor = '    "libavcodec/h264qpel.c",\n'
    if anchor not in src:
        sys.stderr.write(
            f'ERROR: anchor `{anchor.strip()}` not found in {gni_path}. '
            'Upstream Chromium ffmpeg layout may have shifted — review and update '
            'this script.\n'
        )
        return False

    # Defensive: only register paths whose source file actually exists in this checkout
    ffmpeg_dir = gni_path.parent
    paths: list[str] = []
    for direct in HEVC_C_SOURCES_DIRECT:
        if (ffmpeg_dir / direct).is_file():
            paths.append(direct)
        else:
            sys.stderr.write(f'WARN: skipping missing source {direct}\n')
    for base in HEVC_C_SOURCES_AUTORENAME:
        target = ffmpeg_dir / 'libavcodec' / 'hevc' / base
        if target.is_file():
            paths.append(autorename_path(base))
        else:
            sys.stderr.write(f'WARN: skipping missing source libavcodec/hevc/{base}\n')
    # Stub file is dropped by write_simd_stub() before this runs.
    if (ffmpeg_dir / SIMD_STUB_REL_PATH).is_file():
        paths.append(SIMD_STUB_REL_PATH)

    if not paths:
        sys.stderr.write('ERROR: no HEVC sources resolved — bailing\n')
        return False

    insert = ''.join(f'    "{p}",\n' for p in paths)
    out = src.replace(anchor, anchor + insert, 1)
    gni_path.write_text(out)
    return True


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        sys.stderr.write(
            f'Usage: {argv[0]} <chromium/src/third_party/ffmpeg path>\n'
        )
        return 2
    ffmpeg_dir = Path(argv[1]).resolve()
    if not (ffmpeg_dir / 'ffmpeg_generated.gni').is_file():
        sys.stderr.write(f'ERROR: {ffmpeg_dir} does not look like a ffmpeg checkout\n')
        return 2

    # 1. Per-config-dir: config.h + config_components.h + the codec/parser/bsf lists.
    touched = 0
    for cfg_rel in TARGET_CONFIG_DIRS:
        cfg_dir = ffmpeg_dir / cfg_rel
        if not cfg_dir.is_dir():
            print(f'skip {cfg_rel} (does not exist)')
            continue
        for header in ('config.h', 'config_components.h'):
            if patch_config_h(cfg_dir / header):
                print(f'patched {cfg_rel}/{header}')
                touched += 1
        patch_lists(cfg_dir)
        print(f'patched lists under {cfg_rel}/libavcodec/')

    # 2. BUILD.gn — add libavcodec/ to include_dirs so HEVC sources can find
    # parent libavcodec/ headers like progressframe.h.
    if patch_build_gn(ffmpeg_dir / 'BUILD.gn'):
        print('patched BUILD.gn (added libavcodec to include_dirs)')
        touched += 1

    # 2b. chromium/src patches — lift the WebCodecs FFmpegVideoDecoder
    # H.264-only gate so HEVC SW decoding is exposed to JS.
    chromium_src = ffmpeg_dir.parent.parent  # third_party/ffmpeg → src
    if patch_chromium_ffmpeg_video_decoder(chromium_src):
        print('patched chromium/src/media/filters/ffmpeg_video_decoder.cc')
        touched += 1

    # 3. SIMD-init stub — provides empty ff_hevc_dsp_init_{x86,aarch64,arm}.
    if write_simd_stub(ffmpeg_dir):
        print(f'wrote SIMD stub at {SIMD_STUB_REL_PATH}')
        touched += 1

    # 4. autorename wrappers — needed for every libavcodec/hevc/<base>.c whose
    # basename collides with a libavcodec/<base>.c in the same target.
    written = write_autorename_wrappers(ffmpeg_dir)
    if written:
        print(f'created {written} autorename wrapper(s) under libavcodec/')
        touched += written

    # 3. ffmpeg_generated.gni — add HEVC C source paths to the Chrome block.
    gni = ffmpeg_dir / 'ffmpeg_generated.gni'
    if patch_generated_gni(gni):
        print(f'patched {gni.name}')
        touched += 1
    else:
        print(f'{gni.name} already had HEVC entries (no change)')

    print(f'enable-hevc: {touched} file(s) modified')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
