export const buildServerCgiScript = (): string =>
  [
    '#!/bin/sh',
    'PATH=/sbin:/bin:/usr/sbin:/usr/bin',
    '',
    '# LIVI helper CGI',
    '',
    'header() {',
    '  printf "Content-type: text/html\\r\\n\\r\\n"',
    '  echo "<!DOCTYPE html>"',
    '  echo "<html><head><meta charset=\\"utf-8\\"><title>LIVI tools</title>"',
    '  echo "<meta name=\\"viewport\\" content=\\"width=device-width, initial-scale=1\\">"',
    '  echo "<style>',
    '    body{font-family:system-ui,Arial,sans-serif;background:#111;color:#eee;padding:12px;margin:0;}',
    '    h1{font-size:18px;margin:0 0 10px;} h2{font-size:14px;margin:16px 0 8px;}',
    '    a{color:#0bf;text-decoration:none;} a:hover{text-decoration:underline;}',
    '    .bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:8px 0 12px;}',
    '    .chip{display:inline-block;background:#1b1b1b;border:1px solid #2a2a2a;padding:4px 8px;border-radius:8px;}',
    '    .muted{color:#aaa;}',
    '    pre{background:#222;padding:10px;border-radius:10px;white-space:pre-wrap;overflow-x:auto;}',
    '    code{background:#222;padding:2px 4px;border-radius:6px;}',
    '    ul{list-style:none;padding:0;margin:0;}',
    '    li{padding:6px 0;border-bottom:1px solid #1f1f1f;}',
    '    .row{display:flex;justify-content:space-between;gap:12px;align-items:baseline;}',
    '    .name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:75vw;}',
    '    .kind{color:#aaa;font-size:12px;}',
    '  </style>"',
    '  echo "</head><body>"',
    '}',
    '',
    'footer() {',
    '  echo "</body></html>"',
    '}',
    '',
    'htmlesc() {',
    "  printf '%s' \"$1\" | sed 's/&/\\&amp;/g;s/</\\&lt;/g;s/>/\\&gt;/g;s/\"/\\&quot;/g'",
    '}',
    '',
    'urldec() {',
    "  printf '%s' \"$1\" | sed 's/+/ /g;s/%2F/\\//g;s/%20/ /g;s/%25/%/g;s/%23/#/g;s/%3F/?/g;s/%26/\\&/g'",
    '}',
    '',
    'urlenc() {',
    "  printf '%s' \"$1\" | sed 's/%/%25/g;s/ /%20/g;s/#/%23/g;s/?/%3F/g;s/&/%26/g'",
    '}',
    '',
    'nav() {',
    '  echo "<div class=\\"bar\\">"',
    '  echo "<span class=\\"chip\\"><a href=\\"/\\">Home</a></span>"',
    '  echo "<span class=\\"chip\\"><a href=\\"$SCRIPT_NAME\\">Index</a></span>"',
    '  echo "</div>"',
    '}',
    '',
    'show_index() {',
    '  header',
    '  echo "<h1>LIVI / riddle tools</h1>"',
    '  echo "<p class=\\"muted\\">This CGI runs directly on the dongle and has been replaced by LIVI.</p>"',
    '  echo "<ul>"',
    '  echo "<li><a href=\\"$SCRIPT_NAME?action=adv\\">Enable AdvancedFeatures (riddleBoxCfg)</a></li>"',
    '  echo "<li><a href=\\"$SCRIPT_NAME?action=conf\\">Show /etc/riddle.conf</a></li>"',
    '  echo "<li><a href=\\"$SCRIPT_NAME?action=ls&amp;path=/\\">Browse /</a></li>"',
    '  echo "<li><a href=\\"$SCRIPT_NAME?action=ls&amp;path=/etc\\">Browse /etc</a></li>"',
    '  echo "<li><a href=\\"$SCRIPT_NAME?action=ls&amp;path=/tmp\\">Browse /tmp</a></li>"',
    '  echo "</ul>"',
    '  footer',
    '}',
    '',
    'run_adv() {',
    '  header',
    '  val="$v"',
    '  [ -z "$val" ] && val="1"',
    '  case "$val" in 0|1) ;; *) val="1" ;; esac',
    '  echo "<h1>AdvancedFeatures</h1>"',
    '  nav',
    '  echo "<p>Execute <code>riddleBoxCfg -s AdvancedFeatures $val</code></p>"',
    '  /usr/sbin/riddleBoxCfg -s AdvancedFeatures "$val" >/tmp/riddle-adv.log 2>&1',
    '',
    '  if [ -f /tmp/riddle-adv.log ]; then',
    '    echo "<h2>/tmp/riddle-adv.log</h2><pre>"',
    '    sed -n "1,200p" /tmp/riddle-adv.log',
    '    echo "</pre>"',
    '  else',
    '    echo "<p><em>No log found.</em></p>"',
    '  fi',
    '',
    '  if [ -f /etc/riddle.conf ]; then',
    '    echo "<h2>/etc/riddle.conf</h2><pre>"',
    '    sed -n "1,200p" /etc/riddle.conf',
    '    echo "</pre>"',
    '  fi',
    '',
    '  echo "<div class=\\"bar\\"><span class=\\"chip\\"><a href=\\"$SCRIPT_NAME\\">Back</a></span></div>"',
    '  footer',
    '}',
    '',
    'show_conf() {',
    '  header',
    '  echo "<h1>/etc/riddle.conf</h1>"',
    '  nav',
    '  if [ -f /etc/riddle.conf ]; then',
    '    echo "<pre>"',
    '    sed -n "1,200p" /etc/riddle.conf',
    '    echo "</pre>"',
    '  else',
    '    echo "<p>File not found.</p>"',
    '  fi',
    '  echo "<div class=\\"bar\\"><span class=\\"chip\\"><a href=\\"$SCRIPT_NAME\\">Back</a></span></div>"',
    '  footer',
    '}',
    '',
    'view_file() {',
    '  header',
    '  path="$1"',
    '  [ -z "$path" ] && path="/"',
    '  title=$(htmlesc "$path")',
    '  echo "<h1>View $title</h1>"',
    '  nav',
    '',
    '  if [ ! -f "$path" ]; then',
    '    echo "<p>Not a file.</p>"',
    '    footer',
    '    return',
    '  fi',
    '',
    '  echo "<pre>"',
    '  sed -n "1,300p" "$path" 2>&1',
    '  echo "</pre>"',
    '',
    '  echo "<div class=\\"bar\\"><span class=\\"chip\\"><a href=\\"$SCRIPT_NAME?action=ls&amp;path=$(urlenc "$(dirname "$path")")\\">Back to folder</a></span></div>"',
    '  footer',
    '}',
    '',
    'browse() {',
    '  header',
    '  path="$1"',
    '  [ -z "$path" ] && path="/"',
    '',
    '  if [ ! -d "$path" ]; then',
    '    title=$(htmlesc "$path")',
    '    echo "<h1>Browse $title</h1>"',
    '    nav',
    '    echo "<p>Not a directory.</p>"',
    '    footer',
    '    return',
    '  fi',
    '',
    '  clean="$path"',
    '  clean="${clean%/}"',
    '  [ -z "$clean" ] && clean="/"',
    '',
    '  parent="$clean"',
    '  if [ "$parent" != "/" ]; then',
    '    parent="${parent%/*}"',
    '    [ -z "$parent" ] && parent="/"',
    '  fi',
    '',
    '  title=$(htmlesc "$clean")',
    '  echo "<h1>Browse $title</h1>"',
    '  echo "<div class=\\"bar\\">"',
    '  echo "<span class=\\"chip\\"><a href=\\"/\\">Home</a></span>"',
    '  echo "<span class=\\"chip\\"><a href=\\"$SCRIPT_NAME\\">Index</a></span>"',
    '  echo "<span class=\\"chip\\"><a href=\\"$SCRIPT_NAME?action=ls&amp;path=$(urlenc "$parent")\\">Up</a></span>"',
    '  echo "</div>"',
    '',
    '  echo "<ul>"',
    '',
    '  # directories first',
    '  for e in "$clean"/* "$clean"/.*; do',
    '    [ -e "$e" ] || continue',
    '    b="$(basename "$e")"',
    '    [ "$b" = "." ] && continue',
    '    [ "$b" = ".." ] && continue',
    '    if [ -d "$e" ]; then',
    '      be=$(htmlesc "$b")',
    '      pe=$(urlenc "$e")',
    '      echo "<li><div class=\\"row\\"><div class=\\"name\\"><a href=\\"$SCRIPT_NAME?action=ls&amp;path=$pe\\">$be/</a></div><div class=\\"kind\\">dir</div></div></li>"',
    '    fi',
    '  done',
    '',
    '  # then files',
    '  for e in "$clean"/* "$clean"/.*; do',
    '    [ -e "$e" ] || continue',
    '    b="$(basename "$e")"',
    '    [ "$b" = "." ] && continue',
    '    [ "$b" = ".." ] && continue',
    '    if [ -f "$e" ]; then',
    '      be=$(htmlesc "$b")',
    '      pe=$(urlenc "$e")',
    '      echo "<li><div class=\\"row\\"><div class=\\"name\\"><a href=\\"$SCRIPT_NAME?action=view&amp;path=$pe\\">$be</a></div><div class=\\"kind\\">file</div></div></li>"',
    '    fi',
    '  done',
    '',
    '  echo "</ul>"',
    '  footer',
    '}',
    '',
    '# very small query parser for action & path',
    'qs="$QUERY_STRING"',
    'action=""',
    'path=""',
    'v=""',
    '',
    'case "$qs" in',
    '  *action=*)',
    '    action=${qs#*action=}',
    '    action=${action%%&*}',
    '    ;;',
    'esac',
    '',
    'case "$qs" in',
    '  *path=*)',
    '    path=${qs#*path=}',
    '    path=${path%%&*}',
    '    path=$(urldec "$path")',
    '    ;;',
    'esac',
    '',
    'case "$qs" in',
    '  *v=*)',
    '    v=${qs#*v=}',
    '    v=${v%%&*}',
    '    v=$(urldec "$v")',
    '    ;;',
    'esac',
    '',
    'case "$action" in',
    '  adv)   run_adv ;;',
    '  conf)  show_conf ;;',
    '  ls)    browse "$path" ;;',
    '  view)  view_file "$path" ;;',
    '  *)     show_index ;;',
    'esac',
    ''
  ].join('\n')
