export const buildLiviWeb = (): string =>
  [
    '<!doctype html>',
    '<html>',
    '<head>',
    '  <meta charset="utf-8">',
    '  <title>LIVI dongle tools</title>',
    '  <meta name="viewport" content="width=device-width, initial-scale=1">',
    '  <style>',
    '    body{font-family:system-ui,-apple-system,BlinkMacSystemFont,Arial,sans-serif;',
    '         background:#111;color:#eee;margin:0;padding:16px;}',
    '    h1{font-size:20px;margin:0 0 12px;}',
    '    h2{font-size:16px;margin:16px 0 8px;}',
    '    p{margin:4px 0 8px;}',
    '    a{color:#0bf;text-decoration:none;}',
    '    a:hover{text-decoration:underline;}',
    '    code{background:#222;padding:2px 4px;border-radius:3px;font-size:12px;}',
    '    section{margin-bottom:16px;padding:12px;border-radius:8px;background:#181818;}',
    '    form{margin-top:8px;display:flex;gap:8px;flex-wrap:wrap;align-items:center;}',
    '    input[type="text"]{background:#000;border:1px solid #444;border-radius:4px;',
    '                       padding:4px 6px;color:#eee;min-width:180px;}',
    '    button{background:#0bf;border:none;border-radius:4px;padding:4px 10px;',
    '           font-size:13px;color:#000;cursor:pointer;}',
    '    button:hover{filter:brightness(1.1);}',
    '    small{color:#999;font-size:11px;}',
    '  </style>',
    '</head>',
    '<body>',
    '  <h1>LIVI dongle tools</h1>',
    '  <p>This helper page is served directly from the dongle.</p>',
    '  <section>',
    '    <h2>AdvancedFeatures</h2>',
    '    <p>Run <code>riddleBoxCfg -s AdvancedFeatures 0|1</code> and inspect the config:</p>',
    '',
    '    <form method="get" action="./cgi-bin/server.cgi" style="margin:8px 0 4px;">',
    '      <input type="hidden" name="action" value="adv" />',
    '      <input type="hidden" name="v" value="1" />',
    '      <button type="submit">Enable AdvancedFeatures</button>',
    '    </form>',
    '',
    '    <form method="get" action="./cgi-bin/server.cgi" style="margin:0 0 4px;">',
    '      <input type="hidden" name="action" value="adv" />',
    '      <input type="hidden" name="v" value="0" />',
    '      <button type="submit">Disable AdvancedFeatures</button>',
    '    </form>',
    '</section>',
    '',
    '  <section>',
    '    <h2>DashboardInfo</h2>',
    '    <p>Run <code>riddleBoxCfg -s DashboardInfo 0|7</code> and inspect the config:</p>',
    '',
    '    <form method="get" action="./cgi-bin/server.cgi" style="margin:8px 0 4px;">',
    '      <input type="hidden" name="action" value="dbi" />',
    '      <input type="hidden" name="v" value="7" />',
    '      <button type="submit">Enable DashboardInfo</button>',
    '    </form>',
    '',
    '    <form method="get" action="./cgi-bin/server.cgi" style="margin:0 0 4px;">',
    '      <input type="hidden" name="action" value="dbi" />',
    '      <input type="hidden" name="v" value="0" />',
    '      <button type="submit">Disable DashboardInfo</button>',
    '    </form>',
    '</section>',
    '',
    '  <section>',
    '    <h2>Riddle</h2>',
    '    <form method="get" action="./cgi-bin/server.cgi">',
    '      <input type="hidden" name="action" value="conf" />',
    '      <button type="submit">Show /etc/riddle.conf</button>',
    '    </form>',
    '',
    '    <form method="get" action="./cgi-bin/server.cgi">',
    '      <input type="hidden" name="action" value="rbhelp" />',
    '      <button type="submit">Discover riddleBoxCfg options</button>',
    '    </form>',
    '  </section>',
    '',
    '  <section>',
    '    <h2>File browser</h2>',
    '    <p>List files on the dongle using the CGI helper:</p>',
    '',
    '    <form method="get" action="./cgi-bin/server.cgi">',
    '      <input type="hidden" name="action" value="ls" />',
    '      <label for="path"><small>Path</small></label>',
    '      <input id="path" name="path" type="text" value="/etc" />',
    '      <button type="submit">Browse</button>',
    '    </form>',
    '',
    '    <p><small>Example paths: <code>/</code>, <code>/etc</code>, <code>/tmp</code>, <code>/script</code></small></p>',
    '</body>',
    '</html>'
  ].join('\n')
