[package]
name = "livi-aa-stack"
version = "0.1.0"
edition.workspace = true

[dependencies]
livi-aa-proto = { path = "../livi-aa-proto" }
livi-core-proto = { path = "../livi-core-proto" }
livi-session-io = { path = "../livi-session-io" }
livi-wifi = { path = "../livi-wifi" }
prost = "0.14.4"
serde_json = "1.0.151"
tokio = { version = "1.53.2", features = ["rt", "macros", "net", "io-util", "sync", "time"] }

[dev-dependencies]
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time", "test-util"] }
