[package]
name = "iap2-wired"
version = "0.1.0"
edition.workspace = true

[dependencies]
iap2-usbmux = { path = "../iap2-usbmux" }
idevice = { version = "0.1", features = ["pair"] }
plist = "1"
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1", features = ["rt", "sync", "io-util", "time"] }
