// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Action = { "kind": "setConfig", patch: Partial<Config>, } | { "kind": "show", screen: Screen, front: Front, } | { "kind": "media", control: MediaControl, } | { "kind": "seek", positionMs: number, } | { "kind": "selectDevice", id: string, } | { "kind": "forgetDevice", id: string, } | { "kind": "connectDevice", id: string, } | { "kind": "nextDevice" } | { "kind": "applySettings" } | { "kind": "checkUpdate" } | { "kind": "downloadUpdate" } | { "kind": "installUpdate" } | { "kind": "abortUpdate" } | { "kind": "setDongleRadio", radio: Radio, on: boolean, } | { "kind": "quit" } | { "kind": "restart" };

export type AppearanceMode = "auto" | "night" | "day";

export type AudioDevice = { id: string, name: string, isDefault: boolean, 
/**
 * A paired Bluetooth device that is not connected right now.
 */
offline: boolean, };

export enum CarType { "Unknown" = 0, "Gasoline" = 1, "DieselWinter" = 3, "Diesel" = 4, "Biodiesel" = 5, "E85" = 6, "LPG" = 7, "CNG" = 8, "LNG" = 9, "Electric" = 10, "Hydrogen" = 11, "Other" = 12, "HybridGasoline" = 101, "HybridDiesel" = 102 }

export type Config = { debugLogging: boolean, wirelessAaEnabled: boolean, wirelessCpEnabled: boolean, wifiPassword: string, btAdapter: string, wifiInterface: string, wifiDedicatedInterface: boolean, wifiType: WifiBand, wifiChannel: number, wifiChannelWidth: number, country: string, carPlaySourceVersion: string, carPlayMfiI2cBus: number, 
/**
 * -1 when the coprocessor has no power pin.
 */
carPlayMfiPowerGpio: number, gpsEnabled: boolean, gpsDevice: string, gpsBaudRate: number, 
/**
 * From the last GPS fix, applied at startup.
 */
timezone: string, projectionWidth: number, projectionHeight: number, projectionFps: number, projectionDpi: number, projectionViewAreaTop: number, projectionViewAreaBottom: number, projectionViewAreaLeft: number, projectionViewAreaRight: number, projectionSafeAreaTop: number, projectionSafeAreaBottom: number, projectionSafeAreaLeft: number, projectionSafeAreaRight: number, projectionSafeAreaDrawOutside: boolean, clusterWidth: number, clusterHeight: number, clusterFps: number, clusterDpi: number, clusterViewAreaTop: number, clusterViewAreaBottom: number, clusterViewAreaLeft: number, clusterViewAreaRight: number, clusterSafeAreaTop: number, clusterSafeAreaBottom: number, clusterSafeAreaLeft: number, clusterSafeAreaRight: number, lastConnectedAaBtMac?: string, darkMode: boolean, overlayMessages: boolean, displayBrightness: number, displayBrightnessAuto: boolean, 
/**
 * The Wi-Fi AP, Bluetooth and head-unit name, at most 20 characters.
 */
carName: string, oemName: string, hand: HandDriveType, carType?: CarType, evConnectorTypes?: Array<EvConnectorType>, maxSpeedKph: number, 
/**
 * Speed between two numbered marks on the dash, in the unit shown.
 */
speedScaleStep: number, maxRpm: number, 
/**
 * 0 for none.
 */
redlineRpm: number, speedUnit: SpeedUnit, temperatureUnit: TemperatureUnit, samplingFrequency: 0 | 1, disableAudioOutput: boolean, huVolume: number, huVolumeLinkSystem: boolean, audioVolume: number, navVolume: number, voiceAssistantVolume: number, callVolume: number, systemSoundsVolume?: number, audioOutputDevice?: string, audioOutputDeviceLabel?: string, audioInputDevice?: string, audioInputDeviceLabel?: string, visualAudioDelayMs: number, autoConn: boolean, autoSwitchOnReverse: boolean, startPage: string, language: string, kiosk: PerScreen<boolean>, uiZoomPercent: number, appearanceMode: AppearanceMode, 
/**
 * "WIDTHxHEIGHT", empty leaves the panel at the mode it came up in.
 */
displayMode: string, displayGamma: number, displayContrast: number, displayColorR: number, displayColorG: number, displayColorB: number, cameraId: string, camera: PerScreen<boolean>, cameraMirror: boolean, cameraRotation: 0 | 90 | 180 | 270, media: PerScreen<boolean>, dashboards: Dashboards, custom: PerScreen<boolean>, customUrl: string, mainScreenBounds?: WindowBounds, dashScreenBounds?: WindowBounds, auxScreenBounds?: WindowBounds, mainScreenWidth: number, mainScreenHeight: number, dashScreenActive: boolean, dashScreenWidth: number, dashScreenHeight: number, auxScreenActive: boolean, auxScreenWidth: number, auxScreenHeight: number, lastKnownGps?: LastKnownGps, primaryColorDark?: string, primaryColorLight?: string, highlightColorLight?: string, highlightColorDark?: string, backgroundColorDark?: string, backgroundColorLight?: string, 
/**
 * Override for the logo on the CarPlay tile that leads back to LIVI.
 */
carplayIcon120?: string, carplayIcon180?: string, carplayIcon256?: string, updateNightly: boolean, dismissedPackages: Array<string>, bindings: KeyBindings, };

export type DashboardSlot = { main: boolean, dash: boolean, aux: boolean, pos: number, };

export type Dashboards = { dash1: DashboardSlot, dash2: DashboardSlot, dash3: DashboardSlot, dash4: DashboardSlot, };

/**
 * Active projects, available is held or on the access point, offline is
 * only remembered.
 */
export type DeviceStatus = "active" | "available" | "offline";

export type DeviceView = { id: string, name?: string, model?: string, protocol?: Protocol, lastTransport?: string, status: DeviceStatus, batteryLevel?: number, batteryCharging?: boolean, signalStrength?: number, carrierName?: string, 
/**
 * Place among the sessions, counted from 1.
 */
session?: number, };

export type DongleRadios = { wifi: boolean, bt: boolean, };

export enum EvConnectorType { "Unknown" = 0, "J1772" = 1, "Mennekes" = 2, "Chademo" = 3, "Combo1" = 4, "Combo2" = 5, "TeslaSupercharger" = 8, "Gbt" = 9, "Other" = 101 }

export type FromCore = { "type": "welcome", protocol: number, version: string, rev: number, state: State, } | { "type": "refused", reason: string, } | { "type": "patch", rev: number, ops: Array<PatchOp>, } | { "type": "reply", id: number, error?: string, } | { "type": "spectrum", bands: Array<number>, };

export type Front = "livi" | "projection" | "cluster" | "camera";

export enum HandDriveType { "LHD" = 0, "RHD" = 1 }

export type Input = { "kind": "pointer", screen: Screen, points: Array<Point>, } | { "kind": "key", code: string, down: boolean, };

/**
 * Each value is a KeyboardEvent.code, empty when unbound.
 */
export type KeyBindings = { up: string, down: string, left: string, right: string, selectUp: string, selectDown: string, back: string, knobLeft: string, knobRight: string, knobUp: string, knobDown: string, home: string, cycleSession: string, playPause: string, play: string, pause: string, next: string, prev: string, acceptPhone: string, rejectPhone: string, phoneKey0: string, phoneKey1: string, phoneKey2: string, phoneKey3: string, phoneKey4: string, phoneKey5: string, phoneKey6: string, phoneKey7: string, phoneKey8: string, phoneKey9: string, phoneKeyStar: string, phoneKeyHash: string, phoneKeyHookSwitch: string, voiceAssistant: string, voiceAssistantRelease: string, };

export type LastKnownGps = { lat: number, lng: number, alt?: number, heading?: number, 
/**
 * Milliseconds since the epoch.
 */
ts: number, };

/**
 * Down is phone to car, the stream, up is car to phone, touch and mic.
 */
export type LinkSpeed = { downMbps: number, upMbps: number, 
/**
 * The negotiated bitrates, 0 until a phone is on the air.
 */
downRate: number, upRate: number, };

export const MAX_FRAME = 16777216;

export type MediaControl = "playPause" | "play" | "pause" | "next" | "prev";

/**
 * The route guidance of the phone in front, as far as it told.
 */
export type Navigation = { active: boolean | null, orderType: number | null, roadName: string | null, afterRoadName: string | null, destinationName: string | null, timeToDestination: number | null, distanceToDestination: number | null, 
/**
 * To the next maneuver.
 */
remainDistance: number | null, maneuverType: number | null, turnSide: number | null, junctionType: number | null, turnAngle: number | null, 
/**
 * Arrival in Unix seconds, the UI shows it on its own clock.
 */
eta: number | null, 
/**
 * Arrival as the phone wrote it, for a phone that sends no time.
 */
etaText: string | null, appName: string | null, 
/**
 * The phone's own picture of the next maneuver, base64.
 */
image: string | null, 
/**
 * In the UI's language.
 */
maneuverText: string | null, maneuverDistanceText: string | null, destinationDistanceText: string | null, timeLeftText: string | null, };

/**
 * What the phone in front plays, as far as it told.
 */
export type NowPlaying = { title: string | null, artist: string | null, album: string | null, app: string | null, durationMs: number | null, 
/**
 * Where the track was when the phone last said, the UI counts on from there.
 */
elapsedMs: number | null, playing: boolean | null, 
/**
 * Base64 image data.
 */
artwork: string | null, };

export const PROTOCOL = 5;

export type PatchOp = { "op": "set", path: Array<string>, value: unknown, } | { "op": "remove", path: Array<string>, };

export type PerScreen<T> = { main: T, dash: T, aux: T, };

export type Phase = "down" | "move" | "up" | "cancel";

/**
 * Position as a fraction of the screen's content area, 0 to 1.
 */
export type Point = { id: number, x: number, y: number, phase: Phase, };

export type Protocol = "carplay" | "androidauto";

export type Radio = "wifi" | "bt";

export type Release = { version: string, commit: string, 
/**
 * The build number of a nightly.
 */
run: string, 
/**
 * None when the release has no build for this machine.
 */
url: string | null, };

export type Screen = "main" | "dash" | "aux";

export type Sessions = { active: Protocol | null, 
/**
 * Counted from 1, 0 without an active session.
 */
position: number, total: number, };

export type SpeedUnit = "kmh" | "mph";

export type State = { front: PerScreen<Front>, sessions: Sessions, nowPlaying: NowPlaying, navigation: Navigation, system: System, 
/**
 * Those in a session first.
 */
devices: Array<DeviceView>, 
/**
 * What the car and outside producers pushed, merged into one snapshot.
 */
telemetry: Record<string, unknown>, update: Update, config: Config, };

export type System = { 
/**
 * The LIVI Link is among them while it answers.
 */
wifiInterfaces: Array<string>, btAdapters: Array<string>, 
/**
 * The chip behind an interface, by its name, where the system can tell.
 */
interfaceModels: { [key in string]: string }, 
/**
 * None while the LIVI Link does not answer.
 */
dongle: DongleRadios | null, 
/**
 * The phone's Wi-Fi link on the access point.
 */
linkSpeed: LinkSpeed | null, 
/**
 * The bands an access point on the chosen interface can run on.
 */
wifiBands: Array<WifiBand>, 
/**
 * Allowed in the chosen band and country.
 */
wifiChannels: Array<number>, wifiCountries: Array<string>, 
/**
 * The panel's modes as "WIDTHxHEIGHT", largest first.
 */
displayModes: Array<string>, 
/**
 * Under GNOME the modes are only shown, LIVI cannot put the panel into one.
 */
displayModeSettable: boolean, audioSinks: Array<AudioDevice>, audioSources: Array<AudioDevice>, };

export type TemperatureUnit = "celsius" | "fahrenheit";

export type ToCore = { "type": "hello", protocol: number, client: string, } | { "type": "resync" } | { "type": "input", input: Input, } | { "type": "action", id: number, action: Action, } | { "type": "path", path: string, } | { "type": "spectrum", on: boolean, } | { "type": "linkSpeed", on: boolean, };

export type Update = { 
/**
 * On the chosen channel, as the last check found it.
 */
latest: Release | null, checking: boolean, 
/**
 * Also true when the feed did not answer.
 */
checked: boolean, phase: UpdatePhase, received: number, 
/**
 * 0 while the server did not say how big the download is.
 */
total: number, error: string | null, };

export type UpdatePhase = "idle" | "download" | "ready" | "installing" | "relaunching" | "error";

export type WifiBand = "2.4ghz" | "5ghz" | "6ghz";

export type WindowBounds = { x: number, y: number, width: number, height: number, };
