// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Lasse Heitgres

syntax = "proto2";

package livi.aa;

enum MessageStatus {
  MESSAGE_STATUS_UNSOLICITED_MESSAGE = 1;
  MESSAGE_STATUS_SUCCESS = 0;
  MESSAGE_STATUS_NO_COMPATIBLE_VERSION = -1;
  MESSAGE_STATUS_CERTIFICATE_ERROR = -2;
  MESSAGE_STATUS_AUTHENTICATION_FAILURE = -3;
  MESSAGE_STATUS_INVALID_SERVICE = -4;
  MESSAGE_STATUS_INVALID_CHANNEL = -5;
  MESSAGE_STATUS_INVALID_PRIORITY = -6;
  MESSAGE_STATUS_INTERNAL_ERROR = -7;
  MESSAGE_STATUS_MEDIA_CONFIG_MISMATCH = -8;
  MESSAGE_STATUS_INVALID_SENSOR = -9;
  MESSAGE_STATUS_BLUETOOTH_PAIRING_DELAYED = -10;
  MESSAGE_STATUS_BLUETOOTH_UNAVAILABLE = -11;
  MESSAGE_STATUS_BLUETOOTH_INVALID_ADDRESS = -12;
  MESSAGE_STATUS_BLUETOOTH_INVALID_PAIRING_METHOD = -13;
  MESSAGE_STATUS_BLUETOOTH_INVALID_AUTH_DATA = -14;
  MESSAGE_STATUS_BLUETOOTH_AUTH_DATA_MISMATCH = -15;
  MESSAGE_STATUS_BLUETOOTH_HFP_ANOTHER_CONNECTION = -16;
  MESSAGE_STATUS_BLUETOOTH_HFP_CONNECTION_FAILURE = -17;
  MESSAGE_STATUS_KEYCODE_NOT_BOUND = -18;
  MESSAGE_STATUS_RADIO_INVALID_STATION = -19;
  MESSAGE_STATUS_INVALID_INPUT = -20;
  MESSAGE_STATUS_RADIO_STATION_PRESETS_NOT_SUPPORTED = -21;
  MESSAGE_STATUS_RADIO_COMM_ERROR = -22;
  MESSAGE_STATUS_AUTHENTICATION_FAILURE_CERT_NOT_YET_VALID = -23;
  MESSAGE_STATUS_AUTHENTICATION_FAILURE_CERT_EXPIRED = -24;
  MESSAGE_STATUS_PING_TIMEOUT = -25;
  MESSAGE_STATUS_CAR_PROPERTY_SET_REQUEST_FAILED = -26;
  MESSAGE_STATUS_CAR_PROPERTY_LISTENER_REGISTRATION_FAILED = -27;
  MESSAGE_STATUS_COMMAND_NOT_SUPPORTED = -250;
  MESSAGE_STATUS_FRAMING_ERROR = -251;
  MESSAGE_STATUS_UNEXPECTED_MESSAGE = -253;
  MESSAGE_STATUS_BUSY = -254;
  MESSAGE_STATUS_OUT_OF_MEMORY = -255;
}
